### ISSUE TITLE
[Feature-Request]  Afficher la première colonne de la grille dans le nom des notes

### ISSUE THREAD

**Issue by bretonjustin** [blade3/BetterNote#9]
La première colonne de la grille de notes n'apparaît pas nulle part. Dans plusieurs cas il s'agit de détail sur la note (ex. Première colonne: APP3 elec, deuxième colonne: Rapport)
En ce moment il est seulement afficher "Rapport", ce qui donne peu d'informations sur la note.
Thanks keep the good work

**Comment by blade3** [comment]
- Ajouté dans la version 2.3.2

faut que tu active le paramètre "afficher la catégorie"
